spring:
  #profiles: dev
  datasource:
    url: jdbc:mysql://localhost:13306/uaa_srv?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: '1'
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8088